language: minimal

# Only build tags
if: tag IS present
 
addons:
  apt:
    packages:
    - luarocks

install: luarocks install --local luacheck

script:
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -m .pkgmeta
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 1.13.2 -m .pkgmeta-classic
 
notifications:
 email:
   on_success: never
   on_failure: always